name: howdoi
base: core18
version: 'git'
summary: instant coding answers via the command line
description: |
  Are you a hack programmer? Do you find yourself constantly Googling
  for how to do basic programming tasks? Suppose you want to know how
  to format a date in bash. Why open your browser and read through blogs
  (risking major distraction) when you can simply stay in the console
  and ask howdoi.

grade: stable
confinement: strict

parts:
  howdoi:
    plugin: python
    source: .

apps:
  howdoi:
    command: bin/howdoi
    plugs:
      - network